{
    "configurations": [
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python Debugger: Virtac",
            "type": "debugpy",
            "request": "launch",
            "program": "/venv/bin/virtac",
            "console": "integratedTerminal",
            "env": {
                "EPICS_CA_SERVER_PORT": "7064",
                "EPICS_CA_REPEATER_PORT": "7065",
            },
        },
        {
            "name": "Debug Unit Test",
            "type": "debugpy",
            "request": "launch",
            "justMyCode": false,
            "program": "${file}",
            "purpose": [
                "debug-test"
            ],
            "console": "integratedTerminal",
            "env": {
                // Enable break on exception when debugging tests (see: tests/conftest.py)
                "PYTEST_RAISE": "1",
                "EPICS_CA_SERVER_PORT": "7064",
                "EPICS_CA_REPEATER_PORT": "7065",
            },
        }
    ]
}
